# Generated by Django 4.0.4 on 2022-07-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_alter_subcategory_catnm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('ptitle', models.CharField(max_length=50)),
                ('psubcategory', models.CharField(max_length=50)),
                ('pcategory', models.CharField(max_length=100)),
                ('pdescription', models.CharField(max_length=500)),
                ('pprice', models.IntegerField()),
                ('uid', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
